### ISSUE TITLE
static internal ip

### ISSUE THREAD

**Issue by angelbarrera92** [fire1ce/cloudflareDDNS-Bash#4]
Hi!

Did you consider using a static IP for the internal IP option? I mean, instead of trying to guess what (private) IP is running the script, maybe you need to use a different and static IP for a certain domain.

Use case:

- Im using a raspberry pi as VPN and DDNS. It runs in this script at 192.168.111.111.
- I want to point internal.mydomain.io to 192.168.112.112 where is my internal load balancer for Kubernetes.

Do you think it could be possible to implement?

Thanks

**Comment by fire1ce** [comment]
@angelbarrera92 Hey. 
The "guess" is the primery routing of the local ip. 
The use case you mentioned isn't the main purpose of this script. so it won't be implemented.
